### PR TITLE
Autocomplete

### PR DESCRIPTION
**Pull request by twalk4821**
The solution is not perfect; it relies on a timeout to make sure the maps api has loaded before attempting to attach the event listener on the form. There is probably a better work around than this.

### CODE REVIEW

**Comment by ijongkim** [comment]
Hi Tyler, what's the expected behavior? I don't seem to be seeing any action on the test app on Heroku. Maybe I'm using it wrong?

**Comment by twalk4821** [comment]
If you start typing an address in the form just below the the login but above the "name: " input, autocomplete should provide a drop down list of suggestions, which if you click one then automatically fills in the anchor form.

**Comment by ijongkim** [comment]
I am getting errors trying to access autocomplete.js from the test app on heroku. Are you getting the any errors in that environment?

**Comment by twalk4821** [comment]
it seems to be working for me. That error is because I forgot to delete autocomplete.js from the source files: it is now integrated with the anchorbar rather than as a seperate div.

**Pull request closed without merging**
